nelmio_api_doc:
    areas:
        path_patterns:
            - ^/api(?!/doc$)
    documentation:
        info:
            title: ToDo api
            description: API using Symfony framework
            version: 1.0.1
        securityDefinitions:
            ApiAuth:
                type: apiKey
                name: x-api-key
                in: header

        paths:
            /api/users:
                post:
                    tags:
                        - User API
                    description: Registration new user
                    produces:
                        - application/json
                    parameters:
                        - name: user
                          description: User to be registered
                          in: body
                          required: true
                          schema:
                              type: object
                              properties:
                                  email:
                                      type: string
                                  plainPassword:
                                      type: string
                    responses:
                        '200':
                            description: Registration successful
                            schema:
                                type: object
                                properties:
                                    apiToken:
                                        type: string
                        '400':
                            description: Bad request
            /api/users/login:
                post:
                    tags:
                        - User API
                    description: User login
                    produces:
                        - application/json
                    parameters:
                        - name: credentials
                          description: Credentials to login
                          in: body
                          required: true
                          schema:
                              type: object
                              properties:
                                  email:
                                      type: string
                                  plainPassword:
                                      type: string
                    responses:
                        '200':
                            description: Login successful
                            schema:
                                type: object
                                properties:
                                    apiToken:
                                        type: string
                        '400':
                            description: Bad request or credentials
            /api/lists:
                post:
                    tags:
                        - ItemList API
                    parameters:
                        - name: ItemList
                          description: ItemList to be created
                          in: body
                          required: true
                          schema:
                              type: object
                              properties:
                                  title:
                                      type: string
#                                  labels:
#                                      type: array
#                                      items:
#                                          type: object
#                                          properties:
#                                              title:
#                                                  type: string
                    responses:
                        '200':
                            description: List have been successfully created
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: integer
                                    title:
                                        type: string
                        '400':
                            description: Bad request
                    security:
                        - ApiAuth: []
                get:
                    tags:
                        - ItemList API
                    parameters:
                        - name: startId
                          description: First list to be showed
                          in: query
                          required: false
                          type: integer
                        - name: listsNumber
                          description: Number of lists to be showed
                          in: query
                          required: false
                          type: integer
                    responses:
                        '200':
                            description: User's lists
                            schema:
                                type: array
                                items:
                                    type: object
                                    properties:
                                        id:
                                            type: integer
                                        title:
                                            type: string
                        '400':
                            description: Bad request
                    security:
                        - ApiAuth: []
            /api/lists/{id}:
                delete:
                    tags:
                        - ItemList API
                    parameters:
                        - name: id
                          description: Id of list to be deleted
                          in: path
                          required: true
                          type: integer
                    responses:
                        '200':
                            description: List have been successfully deleted
                        '400':
                            description: Bad request
                    security:
                        - ApiAuth: []
                put:
                    tags:
                        - ItemList API
                    parameters:
                        - name: id
                          description: Id of list to be edit
                          in: path
                          required: true
                          type: integer
                        - name: title
                          description: New title of list
                          in: query
                          required: true
                          type: string
                    responses:
                        '200':
                            description: List have been successfully edited
                        '400':
                            description: Bad request
                    security:
                        - ApiAuth: []