nelmio_api_doc:
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
    documentation:
        info:
            title: ToDo api
            description: API using Symfony framework
            version: 1.0.1
        securityDefinitions:
            ApiAuth:
                type: apiKey
                name: x-api-key
                in: header

        paths:
            /api/users:
                post:
                    tags:
                        - User API
                    description: Registration new user
                    produces:
                        - application/json
                    parameters:
                        - name: user
                          description: User to be registered
                          in: body
                          required: true
                          schema:
                              type: object
                              properties:
                                  email:
                                      type: string
                                  plainPassword:
                                      type: string
                    responses:
                        '200':
                            description: Registration successful
                            schema:
                                type: object
                                properties:
                                    apiToken:
                                        type: string
                        '400':
                            description: Bad request
            /api/users/login:
                post:
                    tags:
                        - User API
                    description: User login
                    produces:
                        - application/json
                    parameters:
                        - name: credentials
                          description: Credentials to login
                          in: body
                          required: true
                          schema:
                              type: object
                              properties:
                                  email:
                                      type: string
                                  plainPassword:
                                      type: string
                    responses:
                        '200':
                            description: Login successful
                            schema:
                                type: object
                                properties:
                                    apiToken:
                                        type: string
                        '400':
                            description: Bad request or credentials
#            /api/lists:
#                post:
#                    parameters:
#                        - name: itemList
#                          description: ItemList to be created
#                          in: body
#                          required: true
#                          schema:
#                              type: object
#                              properties:
#                                  name:
#                                      type: string
#                                  labels:
#                                      type: array
#                                      items:
#                                          type: object
#                                          properties:
#                                              title:
#                                                  type: string
#                    security:
#                        - ApiAuth: []